const { Router } = require('express');
const { requireAuth } = require('../../middleware/authMiddleware');
const { validate } = require('../../middleware/validate');
const { registerSchema, verifyOtpSchema, resendOtpSchema, loginSchema, forgotPasswordSchema, resetPasswordSchema } = require('./validation');
const { registerController, resendOtpController, verifyOtpController, loginController, forgotPasswordController, resetPasswordController, meController } = require('./service');
const router = Router();

/**
 * @openapi
 * /api/auth/register:
 *   post:
 *     tags: [Auth]
 *     summary: Register a new user with email and password
 *     description: |
 *       Creates a new user account and sends a verification OTP to the email.
 *       Validates for duplicate email and username before registration.
 *       Automatically creates a Store; storeId is generated by the system.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, password, firstName, lastName]
 *             properties:
 *               email:
 *                 type: string
 *                 format: email
 *                 example: user@example.com
 *               password:
 *                 type: string
 *                 minLength: 8
 *                 example: Aa112233!
 *                 description: Must contain uppercase, lowercase, number, and special character
 *               firstName:
 *                 type: string
 *                 minLength: 1
 *                 maxLength: 100
 *                 example: John
 *               lastName:
 *                 type: string
 *                 minLength: 1
 *                 maxLength: 100
 *                 example: Doe
 *               phone:
 *                 type: string
 *                 nullable: true
 *                 example: +1234567890
 *                 description: Optional phone number
 *               # storeId is not accepted from the client; generated automatically
 *               username:
 *                 type: string
 *                 minLength: 3
 *                 maxLength: 50
 *                 example: johndoe
 *                 description: Optional, auto-generated from email if not provided
 *               role:
 *                 type: string
 *                 enum: [SUPER_ADMIN, STORE_MANAGER, ASSISTANT_MANAGER, CASHIER, INVENTORY_MANAGER, CUSTOMER_SERVICE]
 *                 default: CASHIER
 *                 example: CASHIER
 *     responses:
 *       201:
 *         description: User registered successfully, OTP sent to email
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/RegisterResponse'
 *       400:
 *         description: Validation error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       409:
 *         description: Duplicate registration detected
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: object
 *                   properties:
 *                     code:
 *                       type: string
 *                       example: EMAIL_EXISTS
 *                     message:
 *                       type: string
 *                       example: Email is already registered
 *       404:
 *         description: Store not found
 */
router.post('/register', validate(registerSchema), registerController);

/**
 * @openapi
 * /api/auth/verify-otp:
 *   post:
 *     tags: [Auth]
 *     summary: Verify OTP and activate user account
 *     description: |
 *       Verifies the OTP code sent to the user's email.
 *       For registration, activates the user account.
 *       For password reset, allows password change.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, code]
 *             properties:
 *               email:
 *                 type: string
 *                 format: email
 *                 example: user@example.com
 *               code:
 *                 type: string
 *                 pattern: '^\d{6}$'
 *                 example: "123456"
 *                 description: 6-digit OTP code
 *               purpose:
 *                 type: string
 *                 enum: [register, reset]
 *                 default: register
 *                 example: register
 *     responses:
 *       200:
 *         description: OTP verified successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Verification successful
 *       400:
 *         description: Invalid or expired OTP code
 */
router.post('/verify-otp', validate(verifyOtpSchema), verifyOtpController);

/**
 * @openapi
 * /api/auth/resend-otp:
 *   post:
 *     tags: [Auth]
 *     summary: Resend OTP code to user's email
 *     description: |
 *       Resends a new OTP code to the user's email address.
 *       Can be used for both registration and password reset purposes.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email]
 *             properties:
 *               email:
 *                 type: string
 *                 format: email
 *                 example: user@example.com
 *               purpose:
 *                 type: string
 *                 enum: [register, reset]
 *                 default: register
 *                 example: register
 *     responses:
 *       200:
 *         description: OTP resent successfully
 *       400:
 *         description: User already verified (for registration)
 *       404:
 *         description: User not found
 */
router.post('/resend-otp', validate(resendOtpSchema), resendOtpController);

/**
 * @openapi
 * /api/auth/login:
 *   post:
 *     tags: [Auth]
 *     summary: Authenticate user and receive JWT token
 *     description: |
 *       Authenticates user with email and password.
 *       Returns JWT token and user information.
 *       Triggers automatic sync on successful login.
 *       Implements account locking after failed attempts.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, password]
 *             properties:
 *               email:
 *                 type: string
 *                 format: email
 *                 example: user@example.com
 *               password:
 *                 type: string
 *                 example: SecurePass123!
 *     responses:
 *       200:
 *         description: Login successful
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/LoginResponse'
 *       400:
 *         description: Validation error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       401:
 *         description: Invalid credentials
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       403:
 *         description: Account not verified
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       423:
 *         description: Account locked
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.post('/login', validate(loginSchema), loginController);

/**
 * @openapi
 * /api/auth/forgot-password:
 *   post:
 *     tags: [Auth]
 *     summary: Request password reset OTP
 *     description: |
 *       Sends a password reset OTP to the user's email if the account exists.
 *       Always returns success to prevent email enumeration.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email]
 *             properties:
 *               email:
 *                 type: string
 *                 format: email
 *                 example: user@example.com
 *     responses:
 *       200:
 *         description: If the email exists, a password reset code has been sent
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: If the email exists, a password reset code has been sent.
 */
router.post('/forgot-password', validate(forgotPasswordSchema), forgotPasswordController);

/**
 * @openapi
 * /api/auth/reset-password:
 *   post:
 *     tags: [Auth]
 *     summary: Reset password using OTP code
 *     description: |
 *       Resets user password using the OTP code sent to email.
 *       Requires valid OTP code and strong password.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, code, newPassword]
 *             properties:
 *               email:
 *                 type: string
 *                 format: email
 *                 example: user@example.com
 *               code:
 *                 type: string
 *                 pattern: '^\d{6}$'
 *                 example: "123456"
 *                 description: 6-digit OTP code
 *               newPassword:
 *                 type: string
 *                 minLength: 8
 *                 example: NewSecurePass123!
 *                 description: Must contain uppercase, lowercase, number, and special character
 *     responses:
 *       200:
 *         description: Password reset successful
 *       400:
 *         description: Invalid code, expired code, or weak password
 */
router.post('/reset-password', validate(resetPasswordSchema), resetPasswordController);

/**
 * @openapi
 * /api/auth/me:
 *   get:
 *     tags: [Auth]
 *     summary: Get current authenticated user profile
 *     description: |
 *       Returns the profile information of the currently authenticated user.
 *       Requires valid JWT token in Authorization header.
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: User profile retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: string
 *                   format: uuid
 *                 email:
 *                   type: string
 *                 username:
 *                   type: string
 *                 firstName:
 *                   type: string
 *                 lastName:
 *                   type: string
 *                 phone:
 *                   type: string
 *                   nullable: true
 *                 role:
 *                   type: string
 *                 storeId:
 *                   type: string
 *                 permissions:
 *                   type: array
 *                   items:
 *                     type: string
 *                 isActive:
 *                   type: boolean
 *                 createdAt:
 *                   type: string
 *                   format: date-time
 *       401:
 *         description: Unauthorized - Invalid or missing token
 *       404:
 *         description: User not found
 */
router.get('/me', requireAuth, meController);

module.exports = router;
